// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv"
dotenv.config();
import { defineConfig } from "prisma/config";

const DATABASE_URL = process.env.DATABASE_URL;
if(!DATABASE_URL){
  throw new Error("DATABASE_URL not found");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env.DATABASE_URL,
  },
});
